const quotes = [
    "Be yourself; everyone else is already taken. - Oscar Wilde",
    "Two things are infinite: the universe and human stupidity; and I'm not sure about the universe. - Albert Einstein",
    "In three words I can sum up everything I've learned about life: it goes on. - Robert Frost",
    "The only way to do great work is to love what you do. - Steve Jobs",
    "To be yourself in a world that is constantly trying to make you something else is the greatest accomplishment. - Ralph Waldo Emerson",
    "Your time is limited, don't waste it living someone else's life. - Steve Jobs",
    "The best way to predict the future is to create it. - Peter Drucker",
    "Success is not final, failure is not fatal: It is the courage to continue that counts. - Winston Churchill",
    "The only limit to our realization of tomorrow will be our doubts of today. - Franklin D. Roosevelt",
    "The way to get started is to quit talking and begin doing. - Walt Disney",
    "Don't watch the clock; do what it does. Keep going. - Sam Levenson",
    "It always seems impossible until it's done. - Nelson Mandela",
    "Life is what happens when you're busy making other plans. - Allen Saunders",
    "Your work is going to fill a large part of your life, and the only way to be truly satisfied is to do what you believe is great work. - Steve Jobs",
    "You miss 100% of the shots you don't take. - Wayne Gretzky",
    "The purpose of our lives is to be happy. - Dalai Lama",
    "Strive not to be a success, but rather to be of value. - Albert Einstein",
    "I am not a product of my circumstances. I am a product of my decisions. - Stephen R. Covey",
    "Life is really simple, but we insist on making it complicated. - Confucius",
    "Do not dwell in the past, do not dream of the future, concentrate the mind on the present moment. - Buddha",
    "Believe you can and you're halfway there. - Theodore Roosevelt",
    "The only person you are destined to become is the person you decide to be. - Ralph Waldo Emerson",
    "The best revenge is to be unlike him who performed the injustice. - Marcus Aurelius",
    "The future belongs to those who believe in the beauty of their dreams. - Eleanor Roosevelt",
    "Don't cry because it's over, smile because it happened. - Dr. Seuss",
    "I've learned that people will forget what you said, people will forget what you did, but people will never forget how you made them feel. - Maya Angelou",
    "Success is stumbling from failure to failure with no loss of enthusiasm. - Winston Churchill",
    "Twenty years from now you will be more disappointed by the things that you didn't do than by the ones you did do. - Mark Twain",
    "It's not whether you get knocked down, it's whether you get up. - Vince Lombardi",
    "You can never cross the ocean until you have the courage to lose sight of the shore. - Christopher Columbus",
    "In the end, we will remember not the words of our enemies, but the silence of our friends. - Martin Luther King Jr.",
    "Do not wait to strike till the iron is hot, but make it hot by striking. - William Butler Yeats",
    "Don't aim for success if you want it; just do what you love and believe in, and it will come naturally. - David Frost",
    "The only limit to our realization of tomorrow will be our doubts of today. - Franklin D. Roosevelt",
    "A journey of a thousand miles begins with a single step. - Lao Tzu",
    "The only person you are destined to become is the person you decide to be. - Ralph Waldo Emerson",
    "If you want to achieve greatness stop asking for permission. - Anonymous",
    "The best revenge is to be unlike him who performed the injustice. - Marcus Aurelius",
    "Success usually comes to those who are too busy to be looking for it. - Henry David Thoreau",
    "If you are not willing to risk the usual, you will have to settle for the ordinary. - Jim Rohn",
    "The only way to do great work is to love what you do. - Steve Jobs",
    "Don't be pushed around by the fears in your mind. Be led by the dreams in your heart. - Roy T. Bennett",
    "Good things come to people who wait, but better things come to those who go out and get them. - Anonymous",
    "The future belongs to those who believe in the beauty of their dreams. - Eleanor Roosevelt",
    "Strive not to be a success, but rather to be of value. - Albert Einstein",
    "Believe you can and you're halfway there. - Theodore Roosevelt",
    "If you can dream it, you can do it. - Walt Disney",
    "I find that the harder I work, the more luck I seem to have. - Thomas Jefferson",
    "It's not about how hard you hit. It's about how hard you can get hit and keep moving forward. - Rocky Balboa",
    "Don't let the fear of losing be greater than the excitement of winning. - Robert Kiyosaki",
    "Opportunities don't happen. You create them. - Chris Grosser",
    "I attribute my success to this: I never gave or took any excuse. - Florence Nightingale",
    "I wake up every morning and think to myself, 'How far can I push this company in the next 24 hours?' - Leah Busque",
    "Your time is limited, don't waste it living someone else's life. - Steve Jobs",
    "You don't have to be great to start, but you have to start to be great. - Zig Ziglar",
    "The successful warrior is the average man, with laser-like focus. - Bruce Lee",
    "People who succeed have momentum. The more they succeed, the more they want to succeed, and the more they find a way to succeed. - Tony Robbins",
    "The only place where success comes before work is in the dictionary. - Vidal Sassoon",
    "Success is not in what you have, but who you are. - Bo Bennett",
    "Don't be afraid to give up the good to go for the great. - John D. Rockefeller",
    "Success is not final, failure is not fatal: It is the courage to continue that counts. - Winston Churchill",
    "Success is not the key to happiness. Happiness is the key to success. If you love what you are doing, you will be successful. - Albert Schweitzer",
    "Success usually comes to those who are too busy to be looking for it. - Henry David Thoreau",
    "I find that the harder I work, the more luck I seem to have. - Thomas Jefferson",
    "The only way to achieve the impossible is to believe it is possible. - Charles Kingsleigh",
    "I am not a product of my circumstances. I am a product of my decisions. - Stephen R. Covey",
    "The best way to predict the future is to create it. - Peter Drucker",
    "The only limit to our realization of tomorrow will be our doubts of today. - Franklin D. Roosevelt",
    "The only person you are destined to become is the person you decide to be. - Ralph Waldo Emerson",
    "The best revenge is to be unlike him who performed the injustice. - Marcus Aurelius",
    "Success usually comes to those who are too busy to be looking for it. - Henry David Thoreau",
    "If you are not willing to risk the usual, you will have to settle for the ordinary. - Jim Rohn",
    "The only way to do great work is to love what you do. - Steve Jobs",
    "Don't be pushed around by the fears in your mind. Be led by the dreams in your heart. - Roy T. Bennett",
    "Good things come to people who wait, but better things come to those who go out and get them. - Anonymous",
    "The future belongs to those who believe in the beauty of their dreams. - Eleanor Roosevelt",
    "Strive not to be a success, but rather to be of value. - Albert Einstein",
    "Believe you can and you're halfway there. - Theodore Roosevelt",
    "If you can dream it, you can do it. - Walt Disney",
    "I find that the harder I work, the more luck I seem to have. - Thomas Jefferson",
    "It's not about how hard you hit. It's about how hard you can get hit and keep moving forward. - Rocky Balboa",
    "Don't let the fear of losing be greater than the excitement of winning. - Robert Kiyosaki",
    "Opportunities don't happen. You create them. - Chris Grosser",
    "I attribute my success to this: I never gave or took any excuse. - Florence Nightingale",
    "I wake up every morning and think to myself, 'How far can I push this company in the next 24 hours?' - Leah Busque",
    "Your time is limited, don't waste it living someone else's life. - Steve Jobs",
    "You don't have to be great to start, but you have to start to be great. - Zig Ziglar",
    "The successful warrior is the average man, with laser-like focus. - Bruce Lee",
    "People who succeed have momentum. The more they succeed, the more they want to succeed, and the more they find a way to succeed. - Tony Robbins",
    "The only place where success comes before work is in the dictionary. - Vidal Sassoon",
    "Success is not in what you have, but who you are. - Bo Bennett",
    "Don't be afraid to give up the good to go for the great. - John D. Rockefeller",
    "Success is not final, failure is not fatal: It is the courage to continue that counts. - Winston Churchill",
    "Success is not the key to happiness. Happiness is the key to success. If you love what you are doing, you will be successful. - Albert Schweitzer",
    "Success usually comes to those who are too busy to be looking for it. - Henry David Thoreau",
    "I find that the harder I work, the more luck I seem to have. - Thomas Jefferson",
    "The only way to achieve the impossible is to believe it is possible. - Charles Kingsleigh",
    "I am not a product of my circumstances. I am a product of my decisions. - Stephen R. Covey",
    "The best way to predict the future is to create it. - Peter Drucker",
    "The only limit to our realization of tomorrow will be our doubts of today. - Franklin D. Roosevelt",
    "The only person you are destined to become is the person you decide to be. - Ralph Waldo Emerson",
    "The best revenge is to be unlike him who performed the injustice. - Marcus Aurelius",
    "Success usually comes to those who are too busy to be looking for it. - Henry David Thoreau",
    "If you are not willing to risk the usual, you will have to settle for the ordinary. - Jim Rohn",
    "The only way to do great work is to love what you do. - Steve Jobs",
    "Don't be pushed around by the fears in your mind. Be led by the dreams in your heart. - Roy T. Bennett",
    "Good things come to people who wait, but better things come to those who go out and get them. - Anonymous",
    "The future belongs to those who believe in the beauty of their dreams. - Eleanor Roosevelt",
    "Strive not to be a success, but rather to be of value. - Albert Einstein",
    "Believe you can and you're halfway there. - Theodore Roosevelt",
    "If you can dream it, you can do it. - Walt Disney",
    "I find that the harder I work, the more luck I seem to have. - Thomas Jefferson",
    "It's not about how hard you hit. It's about how hard you can get hit and keep moving forward. - Rocky Balboa",
    "Don't let the fear of losing be greater than the excitement of winning. - Robert Kiyosaki",
    "Opportunities don't happen. You create them. - Chris Grosser",
    "I attribute my success to this: I never gave or took any excuse. - Florence Nightingale",
    "I wake up every morning and think to myself, 'How far can I push this company in the next 24 hours?' - Leah Busque",
    "Your time is limited, don't waste it living someone else's life. - Steve Jobs",
    "You don't have to be great to start, but you have to start to be great. - Zig Ziglar",
    "The successful warrior is the average man, with laser-like focus. - Bruce Lee",
    "People who succeed have momentum. The more they succeed, the more they want to succeed, and the more they find a way to succeed. - Tony Robbins",
    "The only place where success comes before work is in the dictionary. - Vidal Sassoon",
    "Success is not in what you have, but who you are. - Bo Bennett",
    "Don't be afraid to give up the good to go for the great. - John D. Rockefeller",
    "Success is not final, failure is not fatal: It is the courage to continue that counts. - Winston Churchill",
    "Success is not the key to happiness. Happiness is the key to success. If you love what you are doing, you will be successful. - Albert Schweitzer",
    "Success usually comes to those who are too busy to be looking for it. - Henry David Thoreau",
    "I find that the harder I work, the more luck I seem to have. - Thomas Jefferson",
    "The only way to achieve the impossible is to believe it is possible. - Charles Kingsleigh",
    "I am not a product of my circumstances. I am a product of my decisions. - Stephen R. Covey",
    "The best way to predict the future is to create it. - Peter Drucker",
    "The only limit to our realization of tomorrow will be our doubts of today. - Franklin D. Roosevelt",
    "The only person you are destined to become is the person you decide to be. - Ralph Waldo Emerson",
    "The best revenge is to be unlike him who performed the injustice. - Marcus Aurelius",
    "Success usually comes to those who are too busy to be looking for it. - Henry David Thoreau",
    "If you are not willing to risk the usual, you will have to settle for the ordinary. - Jim Rohn",
    "The only way to do great work is to love what you do. - Steve Jobs",
    "Don't be pushed around by the fears in your mind. Be led by the dreams in your heart. - Roy T. Bennett",
    "Good things come to people who wait, but better things come to those who go out and get them. - Anonymous",
    "The future belongs to those who believe in the beauty of their dreams. - Eleanor Roosevelt",
    "Strive not to be a success, but rather to be of value. - Albert Einstein",
    "Believe you can and you're halfway there. - Theodore Roosevelt",
    "If you can dream it, you can do it. - Walt Disney",
    "I find that the harder I work, the more luck I seem to have. - Thomas Jefferson",
    "It's not about how hard you hit. It's about how hard you can get hit and keep moving forward. - Rocky Balboa",
    "Don't let the fear of losing be greater than the excitement of winning. - Robert Kiyosaki",
    "Opportunities don't happen. You create them. - Chris Grosser",
    "I attribute my success to this: I never gave or took any excuse. - Florence Nightingale",
    "I wake up every morning and think to myself, 'How far can I push this company in the next 24 hours?' - Leah Busque",
    "Your time is limited, don't waste it living someone else's life. - Steve Jobs",
    "You don't have to be great to start, but you have to start to be great. - Zig Ziglar",
    "The successful warrior is the average man, with laser-like focus. - Bruce Lee",
    "People who succeed have momentum. The more they succeed, the more they want to succeed, and the more they find a way to succeed. - Tony Robbins",
    "The only place where success comes before work is in the dictionary. - Vidal Sassoon",
    "Success is not in what you have, but who you are. - Bo Bennett",
    "Don't be afraid to give up the good to go for the great. - John D. Rockefeller",
    "Success is not final, failure is not fatal: It is the courage to continue that counts. - Winston Churchill",
    "Success is not the key to happiness. Happiness is the key to success. If you love what you are doing, you will be successful. - Albert Schweitzer",
    "Success usually comes to those who are too busy to be looking for it. - Henry David Thoreau",
    "I find that the harder I work, the more luck I seem to have. - Thomas Jefferson",
    "The only way to achieve the impossible is to believe it is possible. - Charles Kingsleigh",
    "I am not a product of my circumstances. I am a product of my decisions. - Stephen R. Covey",
    "The best way to predict the future is to create it. - Peter Drucker",
    "The only limit to our realization of tomorrow will be our doubts of today. - Franklin D. Roosevelt",
    "The only person you are destined to become is the person you decide to be. - Ralph Waldo Emerson",
    "The best revenge is to be unlike him who performed the injustice. - Marcus Aurelius",
    "Success usually comes to those who are too busy to be looking for it. - Henry David Thoreau",
    "If you are not willing to risk the usual, you will have to settle for the ordinary. - Jim Rohn",
    "The only way to do great work is to love what you do. - Steve Jobs",
    "Don't be pushed around by the fears in your mind. Be led by the dreams in your heart. - Roy T. Bennett",
    "Good things come to people who wait, but better things come to those who go out and get them. - Anonymous",
    "The future belongs to those who believe in the beauty of their dreams. - Eleanor Roosevelt",
    "Strive not to be a success, but rather to be of value. - Albert Einstein",
    "Believe you can and you're halfway there. - Theodore Roosevelt",
    "If you can dream it, you can do it. - Walt Disney",
    "I find that the harder I work, the more luck I seem to have. - Thomas Jefferson",
    "It's not about how hard you hit. It's about how hard you can get hit and keep moving forward. - Rocky Balboa",
    "Don't let the fear of losing be greater than the excitement of winning. - Robert Kiyosaki",
    "Opportunities don't happen. You create them. - Chris Grosser",
    "I attribute my success to this: I never gave or took any excuse. - Florence Nightingale",
    "I wake up every morning and think to myself, 'How far can I push this company in the next 24 hours?' - Leah Busque",
    "Your time is limited, don't waste it living someone else's life. - Steve Jobs",
    "You don't have to be great to start, but you have to start to be great. - Zig Ziglar",
    "The successful warrior is the average man, with laser-like focus. - Bruce Lee",
    "People who succeed have momentum. The more they succeed, the more they want to succeed, and the more they find a way to succeed. - Tony Robbins",
    "The only place where success comes before work is in the dictionary. - Vidal Sassoon",
    "Success is not in what you have, but who you are. - Bo Bennett",
    "Don't be afraid to give up the good to go for the great. - John D. Rockefeller",
    "Success is not final, failure is not fatal: It is the courage to continue that counts. - Winston Churchill",
    "Success is not the key to happiness. Happiness is the key to success. If you love what you are doing, you will be successful. - Albert Schweitzer",
    "Success usually comes to those who are too busy to be looking for it. - Henry David Thoreau",
    "I find that the harder I work, the more luck I seem to have. - Thomas Jefferson",
    "The only way to achieve the impossible is to believe it is possible. - Charles Kingsleigh",
    "I am not a product of my circumstances. I am a product of my decisions. - Stephen R. Covey",
    "The best way to predict the future is to create it. - Peter Drucker",
    "The only limit to our realization of tomorrow will be our doubts of today. - Franklin D. Roosevelt",
    "The only person you are destined to become is the person you decide to be. - Ralph Waldo Emerson",
    "The best revenge is to be unlike him who performed the injustice. - Marcus Aurelius",
    "Success usually comes to those who are too busy to be looking for it. - Henry David Thoreau",
    "If you are not willing to risk the usual, you will have to settle for the ordinary. - Jim Rohn",
    "The only way to do great work is to love what you do. - Steve Jobs",
    "Don't be pushed around by the fears in your mind. Be led by the dreams in your heart. - Roy T. Bennett",
    "Good things come to people who wait, but better things come to those who go out and get them. - Anonymous",
    "The future belongs to those who believe in the beauty of their dreams. - Eleanor Roosevelt",
    "Strive not to be a success, but rather to be of value. - Albert Einstein",
    "Believe you can and you're halfway there. - Theodore Roosevelt",
    "If you can dream it, you can do it. - Walt Disney",
    "I find that the harder I work, the more luck I seem to have. - Thomas Jefferson",
    "It's not about how hard you hit. It's about how hard you can get hit and keep moving forward. - Rocky Balboa",
    "Don't let the fear of losing be greater than the excitement of winning. - Robert Kiyosaki",
    "Opportunities don't happen. You create them. - Chris Grosser",
    "I attribute my success to this: I never gave or took any excuse. - Florence Nightingale",
    "I wake up every morning and think to myself, 'How far can I push this company in the next 24 hours?' - Leah Busque",
    "Your time is limited, don't waste it living someone else's life. - Steve Jobs",
    "You don't have to be great to start, but you have to start to be great. - Zig Ziglar",
    "The successful warrior is the average man, with laser-like focus. - Bruce Lee",
    "People who succeed have momentum. The more they succeed, the more they want to succeed, and the more they find a way to succeed. - Tony Robbins",
    "The only place where success comes before work is in the dictionary. - Vidal Sassoon",
    "Success is not in what you have, but who you are. - Bo Bennett",
    "Don't be afraid to give up the good to go for the great. - John D. Rockefeller",
    "Success is not final, failure is not fatal: It is the courage to continue that counts. - Winston Churchill",
    "Success is not the key to happiness. Happiness is the key to success. If you love what you are doing, you will be successful. - Albert Schweitzer",
    "Success usually comes to those who are too busy to be looking for it. - Henry David Thoreau",
    "I find that the harder I work, the more luck I seem to have. - Thomas Jefferson",
    "The only way to achieve the impossible is to believe it is possible. - Charles Kingsleigh",
    "I am not a product of my circumstances. I am a product of my decisions. - Stephen R. Covey",
    "The best way to predict the future is to create it. - Peter Drucker",
    "The only limit to our realization of tomorrow will be our doubts of today. - Franklin D. Roosevelt",
    "The only person you are destined to become is the person you decide to be. - Ralph Waldo Emerson",
    "The best revenge is to be unlike him who performed the injustice. - Marcus Aurelius",
    "Success usually comes to those who are too busy to be looking for it. - Henry David Thoreau",
    "If you are not willing to risk the usual, you will have to settle for the ordinary. - Jim Rohn",
    "The only way to do great work is to love what you do. - Steve Jobs",
    "Don't be pushed around by the fears in your mind. Be led by the dreams in your heart. - Roy T. Bennett",
    "Good things come to people who wait, but better things come to those who go out and get them. - Anonymous",
    "The future belongs to those who believe in the beauty of their dreams. - Eleanor Roosevelt",
    "Strive not to be a success, but rather to be of value. - Albert Einstein",
    "Believe you can and you're halfway there. - Theodore Roosevelt",
    "If you can dream it, you can do it. - Walt Disney",
    "I find that the harder I work, the more luck I seem to have. - Thomas Jefferson",
    "It's not about how hard you hit. It's about how hard you can get hit and keep moving forward. - Rocky Balboa",
    "Don't let the fear of losing be greater than the excitement of winning. - Robert Kiyosaki",
    "Opportunities don't happen. You create them. - Chris Grosser",
    "I attribute my success to this: I never gave or took any excuse. - Florence Nightingale",
    "I wake up every morning and think to myself, 'How far can I push this company in the next 24 hours?' - Leah Busque",
    "Your time is limited, don't waste it living someone else's life. - Steve Jobs",
    "You don't have to be great to start, but you have to start to be great. - Zig Ziglar",
    "The successful warrior is the average man, with laser-like focus. - Bruce Lee",
    "People who succeed have momentum. The more they succeed, the more they want to succeed, and the more they find a way to succeed. - Tony Robbins",
    "The only place where success comes before work is in the dictionary. - Vidal Sassoon",
    "Success is not in what you have, but who you are. - Bo Bennett",
    "Don't be afraid to give up the good to go for the great. - John D. Rockefeller",
    "Success is not final, failure is not fatal: It is the courage to continue that counts. - Winston Churchill",
    "Success is not the key to happiness. Happiness is the key to success. If you love what you are doing, you will be successful. - Albert Schweitzer",
    "Success usually comes to those who are too busy to be looking for it. - Henry David Thoreau",
    "I find that the harder I work, the more luck I seem to have. - Thomas Jefferson",
    "The only way to achieve the impossible is to believe it is possible. - Charles Kingsleigh",
    "I am not a product of my circumstances. I am a product of my decisions. - Stephen R. Covey",
    "The best way to predict the future is to create it. - Peter Drucker",
    "The only limit to our realization of tomorrow will be our doubts of today. - Franklin D. Roosevelt",
    "The only person you are destined to become is the person you decide to be. - Ralph Waldo Emerson",
    "The best revenge is to be unlike him who performed the injustice. - Marcus Aurelius",
    "Success usually comes to those who are too busy to be looking for it. - Henry David Thoreau",
    "If you are not willing to risk the usual, you will have to settle for the ordinary. - Jim Rohn",
    "The only way to do great work is to love what you do. - Steve Jobs",
    "Don't be pushed around by the fears in your mind. Be led by the dreams in your heart. - Roy T. Bennett",
    "Good things come to people who wait, but better things come to those who go out and get them. - Anonymous",
    "The future belongs to those who believe in the beauty of their dreams. - Eleanor Roosevelt",
    "Strive not to be a success, but rather to be of value. - Albert Einstein",
    "Believe you can and you're halfway there. - Theodore Roosevelt",
    "If you can dream it, you can do it. - Walt Disney",
    "I find that the harder I work, the more luck I seem to have. - Thomas Jefferson",
    "It's not about how hard you hit. It's about how hard you can get hit and keep moving forward. - Rocky Balboa",
    "Don't let the fear of losing be greater than the excitement of winning. - Robert Kiyosaki",
    "Opportunities don't happen. You create them. - Chris Grosser",
    "I attribute my success to this: I never gave or took any excuse. - Florence Nightingale",
    "I wake up every morning and think to myself, 'How far can I push this company in the next 24 hours?' - Leah Busque",
    "Your time is limited, don't waste it living someone else's life. - Steve Jobs",
    "You don't have to be great to start, but you have to start to be great. - Zig Ziglar",
    "The successful warrior is the average man, with laser-like focus. - Bruce Lee",
    "People who succeed have momentum. The more they succeed, the more they want to succeed, and the more they find a way to succeed. - Tony Robbins",
    "The only place where success comes before work is in the dictionary. - Vidal Sassoon",
    "Success is not in what you have, but who you are. - Bo Bennett",
    "Don't be afraid to give up the good to go for the great. - John D. Rockefeller",
    "Success is not final, failure is not fatal: It is the courage to continue that counts. - Winston Churchill",
    "Success is not the key to happiness. Happiness is the key to success. If you love what you are doing, you will be successful. - Albert Schweitzer",
    "Success usually comes to those who are too busy to be looking for it. - Henry David Thoreau",
    "I find that the harder I work, the more luck I seem to have. - Thomas Jefferson",
    "The only way to achieve the impossible is to believe it is possible. - Charles Kingsleigh",
    "I am not a product of my circumstances. I am a product of my decisions. - Stephen R. Covey",
    "The best way to predict the future is to create it. - Peter Drucker",
    "The only limit to our realization of tomorrow will be our doubts of today. - Franklin D. Roosevelt",
    "The only person you are destined to become is the person you decide to be. - Ralph Waldo Emerson",
    "The best revenge is to be unlike him who performed the injustice. - Marcus Aurelius",
    "Success usually comes to those who are too busy to be looking for it. - Henry David Thoreau",
    "If you are not willing to risk the usual, you will have to settle for the ordinary. - Jim Rohn",
    "The only way to do great work is to love what you do. - Steve Jobs",
    "Don't be pushed around by the fears in your mind. Be led by the dreams in your heart. - Roy T. Bennett",
    "Good things come to people who wait, but better things come to those who go out and get them. - Anonymous",
    "The future belongs to those who believe in the beauty of their dreams. - Eleanor Roosevelt",
    "Strive not to be a success, but rather to be of value. - Albert Einstein",
    "Believe you can and you're halfway there. - Theodore Roosevelt",
    "If you can dream it, you can do it. - Walt Disney",
    "I find that the harder I work, the more luck I seem to have. - Thomas Jefferson",
    "It's not about how hard you hit. It's about how hard you can get hit and keep moving forward. - Rocky Balboa",
    "Don't let the fear of losing be greater than the excitement of winning. - Robert Kiyosaki",
    "Opportunities don't happen. You create them. - Chris Grosser",
    "I attribute my success to this: I never gave or took any excuse. - Florence Nightingale",
    "I wake up every morning and think to myself, 'How far can I push this company in the next 24 hours?' - Leah Busque",
    "Your time is limited, don't waste it living someone else's life. - Steve Jobs",
    "You don't have to be great to start, but you have to start to be great. - Zig Ziglar",
    "The successful warrior is the average man, with laser-like focus. - Bruce Lee",
    "People who succeed have momentum. The more they succeed, the more they want to succeed, and the more they find a way to succeed. - Tony Robbins",
    "The only place where success comes before work is in the dictionary. - Vidal Sassoon",
    "Success is not in what you have, but who you are. - Bo Bennett",
    "Don't be afraid to give up the good to go for the great. - John D. Rockefeller",
    "Success is not final, failure is not fatal: It is the courage to continue that counts. - Winston Churchill",
    "Success is not the key to happiness. Happiness is the key to success. If you love what you are doing, you will be successful. - Albert Schweitzer",
    "Success usually comes to those who are too busy to be looking for it. - Henry David Thoreau",
    "I find that the harder I work, the more luck I seem to have. - Thomas Jefferson",
    "The only way to achieve the impossible is to believe it is possible. - Charles Kingsleigh",
    "I am not a product of my circumstances. I am a product of my decisions. - Stephen R. Covey",
    "The best way to predict the future is to create it. - Peter Drucker",
    "The only limit to our realization of tomorrow will be our doubts of today. - Franklin D. Roosevelt",
    "The only person you are destined to become is the person you decide to be. - Ralph Waldo Emerson",
    "The best revenge is to be unlike him who performed the injustice. - Marcus Aurelius",
    "Success usually comes to those who are too busy to be looking for it. - Henry David Thoreau",
    "If you are not willing to risk the usual, you will have to settle for the ordinary. - Jim Rohn",
    "The only way to do great work is to love what you do. - Steve Jobs",
    "Don't be pushed around by the fears in your mind. Be led by the dreams in your heart. - Roy T. Bennett",
    "Good things come to people who wait, but better things come to those who go out and get them. - Anonymous",
    "The future belongs to those who believe in the beauty of their dreams. - Eleanor Roosevelt",
    "Strive not to be a success, but rather to be of value. - Albert Einstein",
    "Believe you can and you're halfway there. - Theodore Roosevelt",
    "If you can dream it, you can do it. - Walt Disney",
    "I find that the harder I work, the more luck I seem to have. - Thomas Jefferson",
    "It's not about how hard you hit. It's about how hard you can get hit and keep moving forward. - Rocky Balboa",
    "Don't let the fear of losing be greater than the excitement of winning. - Robert Kiyosaki",
    "Opportunities don't happen. You create them. - Chris Grosser",
    "I attribute my success to this: I never gave or took any excuse. - Florence Nightingale",
    "I wake up every morning and think to myself, 'How far can I push this company in the next 24 hours?' - Leah Busque",
    "Your time is limited, don't waste it living someone else's life. - Steve Jobs",
    "You don't have to be great to start, but you have to start to be great. - Zig Ziglar",
    "The successful warrior is the average man, with laser-like focus. - Bruce Lee",
    "People who succeed have momentum. The more they succeed, the more they want to succeed, and the more they find a way to succeed. - Tony Robbins",
    "The only place where success comes before work is in the dictionary. - Vidal Sassoon",
    "Success is not in what you have, but who you are. - Bo Bennett",
    "Don't be afraid to give up the good to go for the great. - John D. Rockefeller",
    "Success is not final, failure is not fatal: It is the courage to continue that counts. - Winston Churchill",
    "Success is not the key to happiness. Happiness is the key to success. If you love what you are doing, you will be successful. - Albert Schweitzer",
    "Success usually comes to those who are too busy to be looking for it. - Henry David Thoreau",
    "I find that the harder I work, the more luck I seem to have. - Thomas Jefferson",
    "The only way to achieve the impossible is to believe it is possible. - Charles Kingsleigh",
    "I am not a product of my circumstances. I am a product of my decisions. - Stephen R. Covey",
    "The best way to predict the future is to create it. - Peter Drucker",
    "The only limit to our realization of tomorrow will be our doubts of today. - Franklin D. Roosevelt",
    "The only person you are destined to become is the person you decide to be. - Ralph Waldo Emerson",
    "The best revenge is to be unlike him who performed the injustice. - Marcus Aurelius",
    "Success usually comes to those who are too busy to be looking for it. - Henry David Thoreau",
    "If you are not willing to risk the usual, you will have to settle for the ordinary. - Jim Rohn",
    "The only way to do great work is to love what you do. - Steve Jobs",
    "Don't be pushed around by the fears in your mind. Be led by the dreams in your heart. - Roy T. Bennett",
    "Good things come to people who wait, but better things come to those who go out and get them. - Anonymous",
    "The future belongs to those who believe in the beauty of their dreams. - Eleanor Roosevelt",
    "Strive not to be a success, but rather to be of value. - Albert Einstein",
    "Believe you can and you're halfway there. - Theodore Roosevelt",
    "If you can dream it, you can do it. - Walt Disney",
    "I find that the harder I work, the more luck I seem to have. - Thomas Jefferson",
    "It's not about how hard you hit. It's about how hard you can get hit and keep moving forward. - Rocky Balboa",
    "Don't let the fear of losing be greater than the excitement of winning. - Robert Kiyosaki",
    "Opportunities don't happen. You create them. - Chris Grosser",
    "I attribute my success to this: I never gave or took any excuse. - Florence Nightingale",
    "I wake up every morning and think to myself, 'How far can I push this company in the next 24 hours?' - Leah Busque",
    "Your time is limited, don't waste it living someone else's life. - Steve Jobs",
    "You don't have to be great to start, but you have to start to be great. - Zig Ziglar",
    "The successful warrior is the average man, with laser-like focus. - Bruce Lee",
    "People who succeed have momentum. The more they succeed, the more they want to succeed, and the more they find a way to succeed. - Tony Robbins",
    "The only place where success comes before work is in the dictionary. - Vidal Sassoon",
    "Success is not in what you have, but who you are. - Bo Bennett",
    "Don't be afraid to give up the good to go for the great. - John D. Rockefeller",
    "Success is not final, failure is not fatal: It is the courage to continue that counts. - Winston Churchill",
    "Success is not the key to happiness. Happiness is the key to success. If you love what you are doing, you will be successful. - Albert Schweitzer",
    "Success usually comes to those who are too busy to be looking for it. - Henry David Thoreau",
    "I find that the harder I work, the more luck I seem to have. - Thomas Jefferson",
    "The only way to achieve the impossible is to believe it is possible. - Charles Kingsleigh",
    "I am not a product of my circumstances. I am a product of my decisions. - Stephen R. Covey",
    "The best way to predict the future is to create it. - Peter Drucker",
    "The only limit to our realization of tomorrow will be our doubts of today. - Franklin D. Roosevelt",
    "The only person you are destined to become is the person you decide to be. - Ralph Waldo Emerson",
    "The best revenge is to be unlike him who performed the injustice. - Marcus Aurelius",
    "Success usually comes to those who are too busy to be looking for it. - Henry David Thoreau",
    "If you are not willing to risk the usual, you will have to settle for the ordinary. - Jim Rohn",
    "The only way to do great work is to love what you do. - Steve Jobs",
    "Don't be pushed around by the fears in your mind. Be led by the dreams in your heart. - Roy T. Bennett",
    "Good things come to people who wait, but better things come to those who go out and get them. - Anonymous",
    "The future belongs to those who believe in the beauty of their dreams. - Eleanor Roosevelt",
    "Strive not to be a success, but rather to be of value. - Albert Einstein",
    "Believe you can and you're halfway there. - Theodore Roosevelt",
    "If you can dream it, you can do it. - Walt Disney",
    "I find that the harder I work, the more luck I seem to have. - Thomas Jefferson",
    "It's not about how hard you hit. It's about how hard you can get hit and keep moving forward. - Rocky Balboa",
    "Don't let the fear of losing be greater than the excitement of winning. - Robert Kiyosaki",
    "Opportunities don't happen. You create them. - Chris Grosser",
    "I attribute my success to this: I never gave or took any excuse. - Florence Nightingale",
    "I wake up every morning and think to myself, 'How far can I push this company in the next 24 hours?' - Leah Busque",
    "Your time is limited, don't waste it living someone else's life. - Steve Jobs",
    "You don't have to be great to start, but you have to start to be great. - Zig Ziglar",
    "The successful warrior is the average man, with laser-like focus. - Bruce Lee",
    "People who succeed have momentum. The more they succeed, the more they want to succeed, and the more they find a way to succeed. - Tony Robbins",
    "The only place where success comes before work is in the dictionary. - Vidal Sassoon",
    "Success is not in what you have, but who you are. - Bo Bennett",
    "Don't be afraid to give up the good to go for the great. - John D. Rockefeller",
    "Success is not final, failure is not fatal: It is the courage to continue that counts. - Winston Churchill",
    "Success is not the key to happiness. Happiness is the key to success. If you love what you are doing, you will be successful. - Albert Schweitzer",
    "Success usually comes to those who are too busy to be looking for it. - Henry David Thoreau",
    "I find that the harder I work, the more luck I seem to have. - Thomas Jefferson",
    "The only way to achieve the impossible is to believe it is possible. - Charles Kingsleigh",
    "I am not a product of my circumstances. I am a product of my decisions. - Stephen R. Covey",
    "The best way to predict the future is to create it. - Peter Drucker",
    "The only limit to our realization of tomorrow will be our doubts of today. - Franklin D. Roosevelt",
    "The only person you are destined to become is the person you decide to be. - Ralph Waldo Emerson",
    "The best revenge is to be unlike him who performed the injustice. - Marcus Aurelius",
    "Success usually comes to those who are too busy to be looking for it. - Henry David Thoreau",
    "If you are not willing to risk the usual, you will have to settle for the ordinary. - Jim Rohn",
    "The only way to do great work is to love what you do. - Steve Jobs",
    "Don't be pushed around by the fears in your mind. Be led by the dreams in your heart. - Roy T. Bennett",
    "Good things come to people who wait, but better things come to those who go out and get them. - Anonymous",
    "The future belongs to those who believe in the beauty of their dreams. - Eleanor Roosevelt",
    "Strive not to be a success, but rather to be of value. - Albert Einstein",
    "Believe you can and you're halfway there. - Theodore Roosevelt",
    "If you can dream it, you can do it. - Walt Disney",
    "I find that the harder I work, the more luck I seem to have. - Thomas Jefferson",
    "It's not about how hard you hit. It's about how hard you can get hit and keep moving forward. - Rocky Balboa",
    "Don't let the fear of losing be greater than the excitement of winning. - Robert Kiyosaki",
    "Opportunities don't happen. You create them. - Chris Grosser",
    "I attribute my success to this: I never gave or took any excuse. - Florence Nightingale",
    "I wake up every morning and think to myself, 'How far can I push this company in the next 24 hours?' - Leah Busque",
    "Your time is limited, don't waste it living someone else's life. - Steve Jobs",
    "You don't have to be great to start, but you have to start to be great. - Zig Ziglar",
    "The successful warrior is the average man, with laser-like focus. - Bruce Lee",
    "People who succeed have momentum. The more they succeed, the more they want to succeed, and the more they find a way to succeed. - Tony Robbins",
    "The only place where success comes before work is in the dictionary. - Vidal Sassoon",
    "Success is not in what you have, but who you are. - Bo Bennett",
    "Don't be afraid to give up the good to go for the great. - John D. Rockefeller",
    "Success is not final, failure is not fatal: It is the courage to continue that counts. - Winston Churchill",
    "Success is not the key to happiness. Happiness is the key to success. If you love what you are doing, you will be successful. - Albert Schweitzer",
    "Success usually comes to those who are too busy to be looking for it. - Henry David Thoreau",
    "I find that the harder I work, the more luck I seem to have. - Thomas Jefferson",
    "The only way to achieve the impossible is to believe it is possible. - Charles Kingsleigh",
    "I am not a product of my circumstances. I am a product of my decisions. - Stephen R. Covey",
    "The best way to predict the future is to create it. - Peter Drucker",
    "The only limit to our realization of tomorrow will be our doubts of today. - Franklin D. Roosevelt",
    "The only person you are destined to become is the person you decide to be. - Ralph Waldo Emerson",
    "The best revenge is to be unlike him who performed the injustice. - Marcus Aurelius",
    "Success usually comes to those who are too busy to be looking for it. - Henry David Thoreau",
    "If you are not willing to risk the usual, you will have to settle for the ordinary. - Jim Rohn",
    "The only way to do great work is to love what you do. - Steve Jobs",
    "Don't be pushed around by the fears in your mind. Be led by the dreams in your heart. - Roy T. Bennett",
    "Good things come to people who wait, but better things come to those who go out and get them. - Anonymous",
    "The future belongs to those who believe in the beauty of their dreams. - Eleanor Roosevelt",
    "Strive not to be a success, but rather to be of value. - Albert Einstein",
    "Believe you can and you're halfway there. - Theodore Roosevelt",
    "If you can dream it, you can do it. - Walt Disney",
    "I find that the harder I work, the more luck I seem to have. - Thomas Jefferson",
    "It's not about how hard you hit. It's about how hard you can get hit and keep moving forward. - Rocky Balboa",
    "Don't let the fear of losing be greater than the excitement of winning. - Robert Kiyosaki",
    "Opportunities don't happen. You create them. - Chris Grosser",
    "I attribute my success to this: I never gave or took any excuse. - Florence Nightingale",
    "I wake up every morning and think to myself, 'How far can I push this company in the next 24 hours?' - Leah Busque",
    "Your time is limited, don't waste it living someone else's life. - Steve Jobs",
    "You don't have to be great to start, but you have to start to be great. - Zig Ziglar",
    "The successful warrior is the average man, with laser-like focus. - Bruce Lee",
    "People who succeed have momentum. The more they succeed, the more they want to succeed, and the more they find a way to succeed. - Tony Robbins",
    "The only place where success comes before work is in the dictionary. - Vidal Sassoon",
    "Success is not in what you have, but who you are. - Bo Bennett",
    "Don't be afraid to give up the good to go for the great. - John D. Rockefeller",
    "Success is not final, failure is not fatal: It is the courage to continue that counts. - Winston Churchill",
    "Success is not the key to happiness. Happiness is the key to success. If you love what you are doing, you will be successful. - Albert Schweitzer",
    "Success usually comes to those who are too busy to be looking for it. - Henry David Thoreau",
    "I find that the harder I work, the more luck I seem to have. - Thomas Jefferson",
    "The only way to achieve the impossible is to believe it is possible. - Charles Kingsleigh",
    "I am not a product of my circumstances. I am a product of my decisions. - Stephen R. Covey",
    "The best way to predict the future is to create it. - Peter Drucker",
    "The only limit to our realization of tomorrow will be our doubts of today. - Franklin D. Roosevelt",
    "The only person you are destined to become is the person you decide to be. - Ralph Waldo Emerson",
    "The best revenge is to be unlike him who performed the injustice. - Marcus Aurelius",
    "Success usually comes to those who are too busy to be looking for it. - Henry David Thoreau",
    "If you are not willing to risk the usual, you will have to settle for the ordinary. - Jim Rohn",
    "The only way to do great work is to love what you do. - Steve Jobs",
    "Don't be pushed around by the fears in your mind. Be led by the dreams in your heart. - Roy T. Bennett",
    "Good things come to people who wait, but better things come to those who go out and get them. - Anonymous",
    "The future belongs to those who believe in the beauty of their dreams. - Eleanor Roosevelt",
    "Strive not to be a success, but rather to be of value. - Albert Einstein",
    "Believe you can and you're halfway there. - Theodore Roosevelt",
    "If you can dream it, you can do it. - Walt Disney",
    "I find that the harder I work, the more luck I seem to have. - Thomas Jefferson",
    "It's not about how hard you hit. It's about how hard you can get hit and keep moving forward. - Rocky Balboa",
    "Don't let the fear of losing be greater than the excitement of winning. - Robert Kiyosaki",
    "Opportunities don't happen. You create them. - Chris Grosser",
    "I attribute my success to this: I never gave or took any excuse. - Florence Nightingale",
    "I wake up every morning and think to myself, 'How far can I push this company in the next 24 hours?' - Leah Busque",
    "Your time is limited, don't waste it living someone else's life. - Steve Jobs",
    "You don't have to be great to start, but you have to start to be great. - Zig Ziglar",
    "The successful warrior is the average man, with laser-like focus. - Bruce Lee",
    "People who succeed have momentum. The more they succeed, the more they want to succeed, and the more they find a way to succeed. - Tony Robbins",
    "The only place where success comes before work is in the dictionary. - Vidal Sassoon",
    "Success is not in what you have, but who you are. - Bo Bennett",
    "Don't be afraid to give up the good to go for the great. - John D. Rockefeller",
    "Success is not final, failure is not fatal: It is the courage to continue that counts. - Winston Churchill",
    "Success is not the key to happiness. Happiness is the key to success. If you love what you are doing, you will be successful. - Albert Schweitzer",
    "Success usually comes to those who are too busy to be looking for it. - Henry David Thoreau",
    "I find that the harder I work, the more luck I seem to have. - Thomas Jefferson",
    "The only way to achieve the impossible is to believe it is possible. - Charles Kingsleigh",
    "I am not a product of my circumstances. I am a product of my decisions. - Stephen R. Covey",
    "The best way to predict the future is to create it. - Peter Drucker",
    "The only limit to our realization of tomorrow will be our doubts of today. - Franklin D. Roosevelt",
    "The only person you are destined to become is the person you decide to be. - Ralph Waldo Emerson",
    "The best revenge is to be unlike him who performed the injustice. - Marcus Aurelius",
    "Success usually comes to those who are too busy to be looking for it. - Henry David Thoreau",
    "If you are not willing to risk the usual, you will have to settle for the ordinary. - Jim Rohn",
    "The only way to do great work is to love what you do. - Steve Jobs",
    "Don't be pushed around by the fears in your mind. Be led by the dreams in your heart. - Roy T. Bennett",
    "Good things come to people who wait, but better things come to those who go out and get them. - Anonymous",
    "The future belongs to those who believe in the beauty of their dreams. - Eleanor Roosevelt",
    "Strive not to be a success, but rather to be of value. - Albert Einstein",
    "Believe you can and you're halfway there. - Theodore Roosevelt",
    "If you can dream it, you can do it. - Walt Disney",
    "I find that the harder I work, the more luck I seem to have. - Thomas Jefferson",
    "It's not about how hard you hit. It's about how hard you can get hit and keep moving forward. - Rocky Balboa",
    "Don't let the fear of losing be greater than the excitement of winning. - Robert Kiyosaki",
    "Opportunities don't happen. You create them. - Chris Grosser",
    "I attribute my success to this: I never gave or took any excuse. - Florence Nightingale",
    "I wake up every morning and think to myself, 'How far can I push this company in the next 24 hours?' - Leah Busque",
    "Your time is limited, don't waste it living someone else's life. - Steve Jobs",
    "You don't have to be great to start, but you have to start to be great. - Zig Ziglar",
    "The successful warrior is the average man, with laser-like focus. - Bruce Lee",
    "People who succeed have momentum. The more they succeed, the more they want to succeed, and the more they find a way to succeed. - Tony Robbins",
    "The only place where success comes before work is in the dictionary. - Vidal Sassoon",
    "Success is not in what you have, but who you are. - Bo Bennett",
    "Don't be afraid to give up the good to go for the great. - John D. Rockefeller",
    "Success is not final, failure is not fatal: It is the courage to continue that counts. - Winston Churchill",
    "Success is not the key to happiness. Happiness is the key to success. If you love what you are doing, you will be successful. - Albert Schweitzer",
    "Success usually comes to those who are too busy to be looking for it. - Henry David Thoreau",
    "I find that the harder I work, the more luck I seem to have. - Thomas Jefferson",
    "The only way to achieve the impossible is to believe it is possible. - Charles Kingsleigh",
    "I am not a product of my circumstances. I am a product of my decisions. - Stephen R. Covey",
    "The best way to predict the future is to create it. - Peter Drucker",
    "The only limit to our realization of tomorrow will be our doubts of today. - Franklin D. Roosevelt",
    "The only person you are destined to become is the person you decide to be. - Ralph Waldo Emerson",
    "The best revenge is to be unlike him who performed the injustice. - Marcus Aurelius",
    "Success usually comes to those who are too busy to be looking for it. - Henry David Thoreau",
    "If you are not willing to risk the usual, you will have to settle for the ordinary. - Jim Rohn",
    "The only way to do great work is to love what you do. - Steve Jobs",
    "Don't be pushed around by the fears in your mind. Be led by the dreams in your heart. - Roy T. Bennett",
    "Good things come to people who wait, but better things come to those who go out and get them. - Anonymous",
    "The future belongs to those who believe in the beauty of their dreams. - Eleanor Roosevelt",
    "Strive not to be a success, but rather to be of value. - Albert Einstein",
    "Believe you can and you're halfway there. - Theodore Roosevelt",
    "If you can dream it, you can do it. - Walt Disney",
    "I find that the harder I work, the more luck I seem to have. - Thomas Jefferson",
    "It's not about how hard you hit. It's about how hard you can get hit and keep moving forward. - Rocky Balboa",
    "Don't let the fear of losing be greater than the excitement of winning. - Robert Kiyosaki",
    "Opportunities don't happen. You create them. - Chris Grosser",
    "I attribute my success to this: I never gave or took any excuse. - Florence Nightingale",
    "I wake up every morning and think to myself, 'How far can I push this company in the next 24 hours?' - Leah Busque",
    "Your time is limited, don't waste it living someone else's life. - Steve Jobs",
    "You don't have to be great to start, but you have to start to be great. - Zig Ziglar",
    "The successful warrior is the average man, with laser-like focus. - Bruce Lee",
    "People who succeed have momentum. The more they succeed, the more they want to succeed, and the more they find a way to succeed. - Tony Robbins",
    "The only place where success comes before work is in the dictionary. - Vidal Sassoon",
    "Success is not in what you have, but who you are. - Bo Bennett",
    "Don't be afraid to give up the good to go for the great. - John D. Rockefeller",
    "Success is not final, failure is not fatal: It is the courage to continue that counts. - Winston Churchill",
    "Success is not the key to happiness. Happiness is the key to success. If you love what you are doing, you will be successful. - Albert Schweitzer",
    "Success usually comes to those who are too busy to be looking for it. - Henry David Thoreau",
    "I find that the harder I work, the more luck I seem to have. - Thomas Jefferson",
    "The only way to achieve the impossible is to believe it is possible. - Charles Kingsleigh",
    "I am not a product of my circumstances. I am a product of my decisions. - Stephen R. Covey",
    "The best way to predict the future is to create it. - Peter Drucker",
    "The only limit to our realization of tomorrow will be our doubts of today. - Franklin D. Roosevelt",
    "The only person you are destined to become is the person you decide to be. - Ralph Waldo Emerson",
    "The best revenge is to be unlike him who performed the injustice. - Marcus Aurelius",
    "Success usually comes to those who are too busy to be looking for it. - Henry David Thoreau",
    "If you are not willing to risk the usual, you will have to settle for the ordinary. - Jim Rohn",
    "The only way to do great work is to love what you do. - Steve Jobs",
    "Don't be pushed around by the fears in your mind. Be led by the dreams in your heart. - Roy T. Bennett",
    "Good things come to people who wait, but better things come to those who go out and get them. - Anonymous",
    "The future belongs to those who believe in the beauty of their dreams. - Eleanor Roosevelt",
    "Strive not to be a success, but rather to be of value. - Albert Einstein",
    "Believe you can and you're halfway there. - Theodore Roosevelt",
    "If you can dream it, you can do it. - Walt Disney",
    "I find that the harder I work, the more luck I seem to have. - Thomas Jefferson",
    "It's not about how hard you hit. It's about how hard you can get hit and keep moving forward. - Rocky Balboa",
    "Don't let the fear of losing be greater than the excitement of winning. - Robert Kiyosaki",
    "Opportunities don't happen. You create them. - Chris Grosser",
    "I attribute my success to this: I never gave or took any excuse. - Florence Nightingale",
    "I wake up every morning and think to myself, 'How far can I push this company in the next 24 hours?' - Leah Busque",
    "Your time is limited, don't waste it living someone else's life. - Steve Jobs",
    "You don't have to be great to start, but you have to start to be great. - Zig Ziglar",
    "The successful warrior is the average man, with laser-like focus. - Bruce Lee",
    "People who succeed have momentum. The more they succeed, the more they want to succeed, and the more they find a way to succeed. - Tony Robbins",
    "The only place where success comes before work is in the dictionary. - Vidal Sassoon",
    "Success is not in what you have, but who you are. - Bo Bennett",
    "Don't be afraid to give up the good to go for the great. - John D. Rockefeller",
    "Success is not final, failure is not fatal: It is the courage to continue that counts. - Winston Churchill",
    "Success is not the key to happiness. Happiness is the key to success. If you love what you are doing, you will be successful. - Albert Schweitzer",
    "Success usually comes to those who are too busy to be looking for it. - Henry David Thoreau",
    "I find that the harder I work, the more luck I seem to have. - Thomas Jefferson",
    "The only way to achieve the impossible is to believe it is possible. - Charles Kingsleigh",
    "I am not a product of my circumstances. I am a product of my decisions. - Stephen R. Covey",
    "The best way to predict the future is to create it. - Peter Drucker",
    "The only limit to our realization of tomorrow will be our doubts of today. - Franklin D. Roosevelt",
    "The only person you are destined to become is the person you decide to be. - Ralph Waldo Emerson",
    "The best revenge is to be unlike him who performed the injustice. - Marcus Aurelius",
    "Success usually comes to those who are too busy to be looking for it. - Henry David Thoreau",
    "If you are not willing to risk the usual, you will have to settle for the ordinary. - Jim Rohn",
    "The only way to do great work is to love what you do. - Steve Jobs",
    "Don't be pushed around by the fears in your mind. Be led by the dreams in your heart. - Roy T. Bennett",
    "Good things come to people who wait, but better things come to those who go out and get them. - Anonymous",
    "The future belongs to those who believe in the beauty of their dreams. - Eleanor Roosevelt",
    "Strive not to be a success, but rather to be of value. - Albert Einstein",
    "Believe you can and you're halfway there. - Theodore Roosevelt",
    "If you can dream it, you can do it. - Walt Disney",
    "I find that the harder I work, the more luck I seem to have. - Thomas Jefferson",
    "It's not about how hard you hit. It's about how hard you can get hit and keep moving forward. - Rocky Balboa",
    "Don't let the fear of losing be greater than the excitement of winning. - Robert Kiyosaki",
    "Opportunities don't happen. You create them. - Chris Grosser",
    "I attribute my success to this: I never gave or took any excuse. - Florence Nightingale",
    "I wake up every morning and think to myself, 'How far can I push this company in the next 24 hours?' - Leah Busque",
    "Your time is limited, don't waste it living someone else's life. - Steve Jobs",
    "You don't have to be great to start, but you have to start to be great. - Zig Ziglar",
    "The successful warrior is the average man, with laser-like focus. - Bruce Lee",
    "People who succeed have momentum. The more they succeed, the more they want to succeed, and the more they find a way to succeed. - Tony Robbins",
    "The only place where success comes before work is in the dictionary. - Vidal Sassoon",
    "Success is not in what you have, but who you are. - Bo Bennett",
    "Don't be afraid to give up the good to go for the great. - John D. Rockefeller",
    "Success is not final, failure is not fatal: It is the courage to continue that counts. - Winston Churchill",
    "Success is not the key to happiness. Happiness is the key to success. If you love what you are doing, you will be successful. - Albert Schweitzer",
    "Success usually comes to those who are too busy to be looking for it. - Henry David Thoreau",
    "I find that the harder I work, the more luck I seem to have. - Thomas Jefferson",
    "The only way to achieve the impossible is to believe it is possible. - Charles Kingsleigh",
    "I am not a product of my circumstances. I am a product of my decisions. - Stephen R. Covey",
    "The best way to predict the future is to create it. - Peter Drucker",
    "The only limit to our realization of tomorrow will be our doubts of today. - Franklin D. Roosevelt",
    "The only person you are destined to become is the person you decide to be. - Ralph Waldo Emerson",
    "The best revenge is to be unlike him who performed the injustice. - Marcus Aurelius",
    "Success usually comes to those who are too busy to be looking for it. - Henry David Thoreau",
    "If you are not willing to risk the usual, you will have to settle for the ordinary. - Jim Rohn",
    "The only way to do great work is to love what you do. - Steve Jobs",
    "Don't be pushed around by the fears in your mind. Be led by the dreams in your heart. - Roy T. Bennett",
    "Good things come to people who wait, but better things come to those who go out and get them. - Anonymous",
    "The future belongs to those who believe in the beauty of their dreams. - Eleanor Roosevelt",
    "Strive not to be a success, but rather to be of value. - Albert Einstein",
    "Believe you can and you're halfway there. - Theodore Roosevelt",
    "If you can dream it, you can do it. - Walt Disney",
    "I find that the harder I work, the more luck I seem to have. - Thomas Jefferson",
    "It's not about how hard you hit. It's about how hard you can get hit and keep moving forward. - Rocky Balboa",
    "Don't let the fear of losing be greater than the excitement of winning. - Robert Kiyosaki",
    "Opportunities don't happen. You create them. - Chris Grosser",
    "I attribute my success to this: I never gave or took any excuse. - Florence Nightingale",
    "I wake up every morning and think to myself, 'How far can I push this company in the next 24 hours?' - Leah Busque",
    "Your time is limited, don't waste it living someone else's life. - Steve Jobs",
    "You don't have to be great to start, but you have to start to be great. - Zig Ziglar",
    "The successful warrior is the average man, with laser-like focus. - Bruce Lee",
    "People who succeed have momentum. The more they succeed, the more they want to succeed, and the more they find a way to succeed. - Tony Robbins",
    "The only place where success comes before work is in the dictionary. - Vidal Sassoon",
    "Success is not in what you have, but who you are. - Bo Bennett",
    "Don't be afraid to give up the good to go for the great. - John D. Rockefeller",
    "Success is not final, failure is not fatal: It is the courage to continue that counts. - Winston Churchill",
    "Success is not the key to happiness. Happiness is the key to success. If you love what you are doing, you will be successful. - Albert Schweitzer",
    "Success usually comes to those who are too busy to be looking for it. - Henry David Thoreau",
    "I find that the harder I work, the more luck I seem to have. - Thomas Jefferson",
    "The only way to achieve the impossible is to believe it is possible. - Charles Kingsleigh",
    "I am not a product of my circumstances. I am a product of my decisions. - Stephen R. Covey",
    "The best way to predict the future is to create it. - Peter Drucker",
    "The only limit to our realization of tomorrow will be our doubts of today. - Franklin D. Roosevelt",
    "The only person you are destined to become is the person you decide to be. - Ralph Waldo Emerson",
    "The best revenge is to be unlike him who performed the injustice. - Marcus Aurelius",
    "Success usually comes to those who are too busy to be looking for it. - Henry David Thoreau",
    "If you are not willing to risk the usual, you will have to settle for the ordinary. - Jim Rohn",
    "The only way to do great work is to love what you do. - Steve Jobs",
    "Don't be pushed around by the fears in your mind. Be led by the dreams in your heart. - Roy T. Bennett",
    "Good things come to people who wait, but better things come to those who go out and get them. - Anonymous",
    "The future belongs to those who believe in the beauty of their dreams. - Eleanor Roosevelt",
    "Strive not to be a success, but rather to be of value. - Albert Einstein",
    "Believe you can and you're halfway there. - Theodore Roosevelt",
    "If you can dream it, you can do it. - Walt Disney",
    "I find that the harder I work, the more luck I seem to have. - Thomas Jefferson",
    "It's not about how hard you hit. It's about how hard you can get hit and keep moving forward. - Rocky Balboa",
    "Don't let the fear of losing be greater than the excitement of winning. - Robert Kiyosaki",
    "Opportunities don't happen. You create them. - Chris Grosser",
    "I attribute my success to this: I never gave or took any excuse. - Florence Nightingale",
    "I wake up every morning and think to myself, 'How far can I push this company in the next 24 hours?' - Leah Busque",
    "Your time is limited, don't waste it living someone else's life. - Steve Jobs",
    "You don't have to be great to start, but you have to start to be great. - Zig Ziglar",
    "The successful warrior is the average man, with laser-like focus. - Bruce Lee",
    "People who succeed have momentum. The more they succeed, the more they want to succeed, and the more they find a way to succeed. - Tony Robbins",
    "The only place where success comes before work is in the dictionary. - Vidal Sassoon",
    "Success is not in what you have, but who you are. - Bo Bennett",
    "Don't be afraid to give up the good to go for the great. - John D. Rockefeller",
    "Success is not final, failure is not fatal: It is the courage to continue that counts. - Winston Churchill",
    "Success is not the key to happiness. Happiness is the key to success. If you love what you are doing, you will be successful. - Albert Schweitzer",
    "Success usually comes to those who are too busy to be looking for it. - Henry David Thoreau",
    "I find that the harder I work, the more luck I seem to have. - Thomas Jefferson",
    "The only way to achieve the impossible is to believe it is possible. - Charles Kingsleigh",
    "I am not a product of my circumstances. I am a product of my decisions. - Stephen R. Covey",
    "The best way to predict the future is to create it. - Peter Drucker",
    "The only limit to our realization of tomorrow will be our doubts of today. - Franklin D. Roosevelt",
    "The only person you are destined to become is the person you decide to be. - Ralph Waldo Emerson",
    "The best revenge is to be unlike him who performed the injustice. - Marcus Aurelius",
    "Success usually comes to those who are too busy to be looking for it. - Henry David Thoreau",
    "If you are not willing to risk the usual, you will have to settle for the ordinary. - Jim Rohn",
    "The only way to do great work is to love what you do. - Steve Jobs",
    "Don't be pushed around by the fears in your mind. Be led by the dreams in your heart. - Roy T. Bennett",
    "Good things come to people who wait, but better things come to those who go out and get them. - Anonymous",
    "The future belongs to those who believe in the beauty of their dreams. - Eleanor Roosevelt",
    "Strive not to be a success, but rather to be of value. - Albert Einstein",
    "Believe you can and you're halfway there. - Theodore Roosevelt",
    "If you can dream it, you can do it. - Walt Disney",
    "I find that the harder I work, the more luck I seem to have. - Thomas Jefferson",
    "It's not about how hard you hit. It's about how hard you can get hit and keep moving forward. - Rocky Balboa",
    "Don't let the fear of losing be greater than the excitement of winning. - Robert Kiyosaki",
    "Opportunities don't happen. You create them. - Chris Grosser",
    "I attribute my success to this: I never gave or took any excuse. - Florence Nightingale",
    "I wake up every morning and think to myself, 'How far can I push this company in the next 24 hours?' - Leah Busque",
    "Your time is limited, don't waste it living someone else's life. - Steve Jobs",
    "You don't have to be great to start, but you have to start to be great. - Zig Ziglar",
    "The successful warrior is the average man, with laser-like focus. - Bruce Lee",
    "People who succeed have momentum. The more they succeed, the more they want to succeed, and the more they find a way to succeed. - Tony Robbins",
    "The only place where success comes before work is in the dictionary. - Vidal Sassoon",
    "Success is not in what you have, but who you are. - Bo Bennett",
    "Don't be afraid to give up the good to go for the great. - John D. Rockefeller",
    "Success is not final, failure is not fatal: It is the courage to continue that counts. - Winston Churchill",
    "Success is not the key to happiness. Happiness is the key to success. If you love what you are doing, you will be successful. - Albert Schweitzer",
    "Success usually comes to those who are too busy to be looking for it. - Henry David Thoreau",
    "I find that the harder I work, the more luck I seem to have. - Thomas Jefferson",
    "The only way to achieve the impossible is to believe it is possible. - Charles Kingsleigh",
    "I am not a product of my circumstances. I am a product of my decisions. - Stephen R. Covey",
    "The best way to predict the future is to create it. - Peter Drucker",
    "The only limit to our realization of tomorrow will be our doubts of today. - Franklin D. Roosevelt",
    "The only person you are destined to become is the person you decide to be. - Ralph Waldo Emerson",
    "The best revenge is to be unlike him who performed the injustice. - Marcus Aurelius",
    "Success usually comes to those who are too busy to be looking for it. - Henry David Thoreau",
    "If you are not willing to risk the usual, you will have to settle for the ordinary. - Jim Rohn",
    "The only way to do great work is to love what you do. - Steve Jobs",
    "Don't be pushed around by the fears in your mind. Be led by the dreams in your heart. - Roy T. Bennett",
    "Good things come to people who wait, but better things come to those who go out and get them. - Anonymous",
    "The future belongs to those who believe in the beauty of their dreams. - Eleanor Roosevelt",
    "Strive not to be a success, but rather to be of value. - Albert Einstein",
    "Believe you can and you're halfway there. - Theodore Roosevelt",
    "If you can dream it, you can do it. - Walt Disney",
    "I find that the harder I work, the more luck I seem to have. - Thomas Jefferson",
    "It's not about how hard you hit. It's about how hard you can get hit and keep moving forward. - Rocky Balboa",
    "Don't let the fear of losing be greater than the excitement of winning. - Robert Kiyosaki",
    "Opportunities don't happen. You create them. - Chris Grosser",
    "I attribute my success to this: I never gave or took any excuse. - Florence Nightingale",
    "I wake up every morning and think to myself, 'How far can I push this company in the next 24 hours?' - Leah Busque",
    "Your time is limited, don't waste it living someone else's life. - Steve Jobs",
    "You don't have to be great to start, but you have to start to be great. - Zig Ziglar",
    "The successful warrior is the average man, with laser-like focus. - Bruce Lee",
    "People who succeed have momentum. The more they succeed, the more they want to succeed, and the more they find a way to succeed. - Tony Robbins",
    "The only place where success comes before work is in the dictionary. - Vidal Sassoon",
    "Success is not in what you have, but who you are. - Bo Bennett",
    "Don't be afraid to give up the good to go for the great. - John D. Rockefeller",
    "Success is not final, failure is not fatal: It is the courage to continue that counts. - Winston Churchill",
    "Success is not the key to happiness. Happiness is the key to success. If you love what you are doing, you will be successful. - Albert Schweitzer",
    "Success usually comes to those who are too busy to be looking for it. - Henry David Thoreau",
    "I find that the harder I work, the more luck I seem to have. - Thomas Jefferson",
    "The only way to achieve the impossible is to believe it is possible. - Charles Kingsleigh",
    "I am not a product of my circumstances. I am a product of my decisions. - Stephen R. Covey",
    "The best way to predict the future is to create it. - Peter Drucker",
    "The only limit to our realization of tomorrow will be our doubts of today. - Franklin D. Roosevelt",
    "The only person you are destined to become is the person you decide to be. - Ralph Waldo Emerson",
    "The best revenge is to be unlike him who performed the injustice. - Marcus Aurelius",
    "Success usually comes to those who are too busy to be looking for it. - Henry David Thoreau",
    "If you are not willing to risk the usual, you will have to settle for the ordinary. - Jim Rohn",
    "The only way to do great work is to love what you do. - Steve Jobs",
    "Don't be pushed around by the fears in your mind. Be led by the dreams in your heart. - Roy T. Bennett",
    "Good things come to people who wait, but better things come to those who go out and get them. - Anonymous",
    "The future belongs to those who believe in the beauty of their dreams. - Eleanor Roosevelt",
    "Strive not to be a success, but rather to be of value. - Albert Einstein",
    "Believe you can and you're halfway there. - Theodore Roosevelt",
    "If you can dream it, you can do it. - Walt Disney",
    "I find that the harder I work, the more luck I seem to have. - Thomas Jefferson",
    "It's not about how hard you hit. It's about how hard you can get hit and keep moving forward. - Rocky Balboa",
    "Don't let the fear of losing be greater than the excitement of winning. - Robert Kiyosaki",
    "Opportunities don't happen. You create them. - Chris Grosser",
    "I attribute my success to this: I never gave or took any excuse. - Florence Nightingale",
    "I wake up every morning and think to myself, 'How far can I push this company in the next 24 hours?' - Leah Busque",
    "Your time is limited, don't waste it living someone else's life. - Steve Jobs",
    "You don't have to be great to start, but you have to start to be great. - Zig Ziglar",
    "The successful warrior is the average man, with laser-like focus. - Bruce Lee",
    "People who succeed have momentum. The more they succeed, the more they want to succeed, and the more they find a way to succeed. - Tony Robbins",
    "The only place where success comes before work is in the dictionary. - Vidal Sassoon",
    "Success is not in what you have, but who you are. - Bo Bennett",
    "Don't be afraid to give up the good to go for the great. - John D. Rockefeller",
    "Success is not final, failure is not fatal: It is the courage to continue that counts. - Winston Churchill",
    "Success is not the key to happiness. Happiness is the key to success. If you love what you are doing, you will be successful. - Albert Schweitzer",
    "Success usually comes to those who are too busy to be looking for it. - Henry David Thoreau",
    "I find that the harder I work, the more luck I seem to have. - Thomas Jefferson",
    "The only way to achieve the impossible is to believe it is possible. - Charles Kingsleigh",
    "I am not a product of my circumstances. I am a product of my decisions. - Stephen R. Covey",
    "The best way to predict the future is to create it. - Peter Drucker",
    "The only limit to our realization of tomorrow will be our doubts of today. - Franklin D. Roosevelt",
    "The only person you are destined to become is the person you decide to be. - Ralph Waldo Emerson",
    "The best revenge is to be unlike him who performed the injustice. - Marcus Aurelius",
    "Success usually comes to those who are too busy to be looking for it. - Henry David Thoreau",
    "If you are not willing to risk the usual, you will have to settle for the ordinary. - Jim Rohn",
    "The only way to do great work is to love what you do. - Steve Jobs",
    "Don't be pushed around by the fears in your mind. Be led by the dreams in your heart. - Roy T. Bennett",
    "Good things come to people who wait, but better things come to those who go out and get them. - Anonymous",
    "The future belongs to those who believe in the beauty of their dreams. - Eleanor Roosevelt",
    "Strive not to be a success, but rather to be of value. - Albert Einstein",
    "Believe you can and you're halfway there. - Theodore Roosevelt",
    "If you can dream it, you can do it. - Walt Disney",
    "I find that the harder I work, the more luck I seem to have. - Thomas Jefferson",
    "It's not about how hard you hit. It's about how hard you can get hit and keep moving forward. - Rocky Balboa",
    "Don't let the fear of losing be greater than the excitement of winning. - Robert Kiyosaki",
    "Opportunities don't happen. You create them. - Chris Grosser",
    "I attribute my success to this: I never gave or took any excuse. - Florence Nightingale",
    "I wake up every morning and think to myself, 'How far can I push this company in the next 24 hours?' - Leah Busque",
    "Your time is limited, don't waste it living someone else's life. - Steve Jobs",
    "You don't have to be great to start, but you have to start to be great. - Zig Ziglar",
    "The successful warrior is the average man, with laser-like focus. - Bruce Lee",
    "People who succeed have momentum. The more they succeed, the more they want to succeed, and the more they find a way to succeed. - Tony Robbins",
    "The only place where success comes before work is in the dictionary. - Vidal Sassoon",
    "Success is not in what you have, but who you are. - Bo Bennett",
    "Don't be afraid to give up the good to go for the great. - John D. Rockefeller",
    "Success is not final, failure is not fatal: It is the courage to continue that counts. - Winston Churchill",
    "Success is not the key to happiness. Happiness is the key to success. If you love what you are doing, you will be successful. - Albert Schweitzer",
    "Success usually comes to those who are too busy to be looking for it. - Henry David Thoreau",
    "I find that the harder I work, the more luck I seem to have. - Thomas Jefferson",
    "The only way to achieve the impossible is to believe it is possible. - Charles Kingsleigh",
    "I am not a product of my circumstances. I am a product of my decisions. - Stephen R. Covey",
    "The best way to predict the future is to create it. - Peter Drucker",
    "The only limit to our realization of tomorrow will be our doubts of today. - Franklin D. Roosevelt",
    "The only person you are destined to become is the person you decide to be. - Ralph Waldo Emerson",
    "The best revenge is to be unlike him who performed the injustice. - Marcus Aurelius",
    "Success usually comes to those who are too busy to be looking for it. - Henry David Thoreau",
    "If you are not willing to risk the usual, you will have to settle for the ordinary. - Jim Rohn",
    "The only way to do great work is to love what you do. - Steve Jobs",
    "Don't be pushed around by the fears in your mind. Be led by the dreams in your heart. - Roy T. Bennett",
    "Good things come to people who wait, but better things come to those who go out and get them. - Anonymous",
    "The future belongs to those who believe in the beauty of their dreams. - Eleanor Roosevelt",
    "Strive not to be a success, but rather to be of value. - Albert Einstein",
    "Believe you can and you're halfway there. - Theodore Roosevelt",
    "If you can dream it, you can do it. - Walt Disney",
    "I find that the harder I work, the more luck I seem to have. - Thomas Jefferson",
    "It's not about how hard you hit. It's about how hard you can get hit and keep moving forward. - Rocky Balboa",
    "Don't let the fear of losing be greater than the excitement of winning. - Robert Kiyosaki",
    "Opportunities don't happen. You create them. - Chris Grosser",
    "I attribute my success to this: I never gave or took any excuse. - Florence Nightingale",
    "I wake up every morning and think to myself, 'How far can I push this company in the next 24 hours?' - Leah Busque",
    "Your time is limited, don't waste it living someone else's life. - Steve Jobs",
    "You don't have to be great to start, but you have to start to be great. - Zig Ziglar",
    "The successful warrior is the average man, with laser-like focus. - Bruce Lee",
    "People who succeed have momentum. The more they succeed, the more they want to succeed, and the more they find a way to succeed. - Tony Robbins",
    "The only place where success comes before work is in the dictionary. - Vidal Sassoon",
    "Success is not in what you have, but who you are. - Bo Bennett",
    "Don't be afraid to give up the good to go for the great. - John D. Rockefeller",
    "Success is not final, failure is not fatal: It is the courage to continue that counts. - Winston Churchill",
    "Success is not the key to happiness. Happiness is the key to success. If you love what you are doing, you will be successful. - Albert Schweitzer",
    "Success usually comes to those who are too busy to be looking for it. - Henry David Thoreau",
    "I find that the harder I work, the more luck I seem to have. - Thomas Jefferson",
    "The only way to achieve the impossible is to believe it is possible. - Charles Kingsleigh",
    "I am not a product of my circumstances. I am a product of my decisions. - Stephen R. Covey",
    "The best way to predict the future is to create it. - Peter Drucker",
    "The only limit to our realization of tomorrow will be our doubts of today. - Franklin D. Roosevelt",
    "The only person you are destined to become is the person you decide to be. - Ralph Waldo Emerson",
    "The best revenge is to be unlike him who performed the injustice. - Marcus Aurelius",
    "Success usually comes to those who are too busy to be looking for it. - Henry David Thoreau",
    "If you are not willing to risk the usual, you will have to settle for the ordinary. - Jim Rohn",
    "The only way to do great work is to love what you do. - Steve Jobs",
    "Don't be pushed around by the fears in your mind. Be led by the dreams in your heart. - Roy T. Bennett",
    "Good things come to people who wait, but better things come to those who go out and get them. - Anonymous",
    "The future belongs to those who believe in the beauty of their dreams. - Eleanor Roosevelt",
    "Strive not to be a success, but rather to be of value. - Albert Einstein",
    "Believe you can and you're halfway there. - Theodore Roosevelt",
    "If you can dream it, you can do it. - Walt Disney",
    "I find that the harder I work, the more luck I seem to have. - Thomas Jefferson",
    "It's not about how hard you hit. It's about how hard you can get hit and keep moving forward. - Rocky Balboa",
    "Don't let the fear of losing be greater than the excitement of winning. - Robert Kiyosaki",
    "Opportunities don't happen. You create them. - Chris Grosser",
    "I attribute my success to this: I never gave or took any excuse. - Florence Nightingale",
    "I wake up every morning and think to myself, 'How far can I push this company in the next 24 hours?' - Leah Busque",
    "Your time is limited, don't waste it living someone else's life. - Steve Jobs",
    "You don't have to be great to start, but you have to start to be great. - Zig Ziglar",
    "The successful warrior is the average man, with laser-like focus. - Bruce Lee",
    "People who succeed have momentum. The more they succeed, the more they want to succeed, and the more they find a way to succeed. - Tony Robbins",
    "The only place where success comes before work is in the dictionary. - Vidal Sassoon",
    "Success is not in what you have, but who you are. - Bo Bennett",
    "Don't be afraid to give up the good to go for the great. - John D. Rockefeller",
    "Success is not final, failure is not fatal: It is the courage to continue that counts. - Winston Churchill",
    "Success is not the key to happiness. Happiness is the key to success. If you love what you are doing, you will be successful. - Albert Schweitzer",
    "Success usually comes to those who are too busy to be looking for it. - Henry David Thoreau",
    "I find that the harder I work, the more luck I seem to have. - Thomas Jefferson",
    "The only way to achieve the impossible is to believe it is possible. - Charles Kingsleigh",
    "I am not a product of my circumstances. I am a product of my decisions. - Stephen R. Covey",
    "The best way to predict the future is to create it. - Peter Drucker",
    "The only limit to our realization of tomorrow will be our doubts of today. - Franklin D. Roosevelt"
]


const quoteText = document.getElementById('quote-text');
const newQuoteBtn = document.getElementById('new-quote-btn');

function getRandomQuote() {
    const randomIndex = Math.floor(Math.random() * quotes.length);
    return quotes[randomIndex];
}

function displayRandomQuote() {
    const randomQuote = getRandomQuote();
    quoteText.textContent = randomQuote;
}

newQuoteBtn.addEventListener('click', displayRandomQuote);

displayRandomQuote();